### ISSUE TITLE
watch throws error

### ISSUE THREAD

**Issue by holtwick** [rsms/estrella#10]
As of 1.2.3 `-watch` throws an error:

```
Unhandled promise rejection: Error: Cannot find module '/Users/dirk/Downloads/ex1/node_modules/estrella/dist/watch.js'
Require stack:
- /Users/dirk/Downloads/ex1/node_modules/estrella/dist/estrella.js
- /Users/dirk/Downloads/ex1/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /Users/dirk/Downloads/ex1/node_modules/estrella/<estrella>/aux.ts:23:11
    at en (/Users/dirk/Downloads/ex1/node_modules/estrella/<estrella>/estrella.js:733:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/49557/94528392-9cfa3700-0238-11eb-8cd6-c308c8774d90.png">

To reproduce set up a minimal project like this:

```
npm init estrella sample
cd sample
npm i
npm start
```

**Comment by rsms** [comment]
Thank you! Fixed in latest release. I forgot to add it to npm's list of "files to be included in package".

**Comment by holtwick** [comment]
Thanks. Works now.
