### ISSUE TITLE
watch: when esbuild fails causes estrella to crash in certain circumstances

### ISSUE THREAD

**Issue by rsms** [rsms/estrella#22]
Repro:

main.js:

```js
import { nonexisting } from "./lib"
console.log(nonexisting)
```

lib.js

```js
export const a = 1
```

Run estrella:

```sh
$ estrella -bundle -o=out.js main.js
 > main.js: error: No matching export for import "nonexisting"
    1 │ import { nonexisting } from "./lib"
      ╵          ~~~~~~~~~~~

../../dist/estrella.g.js: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at refreshFiles (/Users/rsms/src/src/watch/watch.ts:62:29)
    at Object.watchFiles (/Users/rsms/src/src/watch/watch.ts:106:3)
    at build1 (/Users/rsms/src/src/estrella.js:769:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This happens because esbuild doesn't produce a valid (i.e. what estrella expects) metadata file when the build fails.

**Comment by rsms** [comment]
Published in [v1.3.0](https://github.com/rsms/estrella/releases/tag/v1.3.0)
